# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef4e44f6a068f96cd39eba20f9f8fdc2d08cd3666231f586329a7afb886f4969a83ab68ead5a5ace9e3582c1f1dd0279b8a2cea6e090ce2b2c35a232c599a24

test:
  secret_key_base: 720eaf17534dd77f9c6e6d9c6d9efb200233b08ed582562fefa1b261eeb0bf37ffe8487c163db313ee8f0531ab67bbce9aa76c95eb28cda0bd1c205505b4aa07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
